Feature/rss ecomm 43 about page   implement about page
Yuliya-Karuk/eCommerce-Application pull request #47
Opened 2024-06-10 18:37 UTC by GreyAdmiral

Implement about page

2024-06-11 06:42 UTC, Vitali86 submitted a review, later dismissed

2024-06-11 08:11 UTC, Yuliya-Karuk reviewed
Опять какой-то косяк с ПР, ветки нужно ВСЕГДА делать от девелоп, потому что сейчас мы должно опять ревьювать коммиты фиксов из прошлой ветки, и ты их опять будешь мержить, а такого не должны быть, надо мержить тольно новые коммиты

2024-06-11 09:59 UTC, Vitali86 requested changes
не выпонено Issue RSS-ECOMM-4_20: Incorporate and Link RS School Logo on the About Us Page (10 points)

2024-06-16 23:30 UTC, Yuliya-Karuk approved these changes

2024-06-16 23:45 UTC, merged